######################################################################################
## ,--.  ,--.                   ,------.                                            ##
## |  |,-'  '-. ,---. ,--,--,--.|  .--. ' ,---.  ,---.  ,---.,--.,--. ,---. ,--.--. ##
## |  |'-.  .-'| .-. :|        ||  '--'.'| .-. :(  .-' | .--'|  ||  || .-. :|  .--' ##
## |  |  |  |  \   --.|  |  |  ||  |\  \ \   --..-'  `)\ `--.'  ''  '\   --.|  |    ##
## `--'  `--'   `----'`--`--`--'`--' '--' `----'`----'  `---' `----'  `----'`--'    ##
######################################################################################

#ItemRescuer Configuration
itemrescurer:
  #The craft to make the red dye "ItemRescuer" (a.k.a SoundBound)
  craft:
    #Here you can disable the craft
    enabled: false
    #And here you can define the shape of the craft (itemid:itemmetadata)
    shape:
    - 42,341,42
    - 42,351:1,42
    - 42,138,42
  messages:
    respawn:
      #Enable, disable and modify message when player respawn
      string: '&eYou save {COUNT} item/s!'
      enabled: true
    get:
      #Message when you bound item
      string: '&aYou get {AMOUNT} ItemRescuer item'
      denied: '&cYou can''t bound this kind of item'
      #Enable, disable modiify get message
      bound: '&aYou bound {ITEM} succesfully'
      enabled: true
  bound:
    #Bound items in crafting table
    craft: true
    #Bound items with drag and drop in inventory
    drop: true
  #This message display when you have a item rescuer with 1 use and you die
  break: '&cOne item has been unbounded!'
  #The lore for mark it a soulbounded item (You can change it anytime you wan't and the items go to work anyway (The only problem is soulbounds with uses))
  markeditem: '&9SoulBound: &6{PLAYER}'
  #ItemRescuer item (Default: Red Dye)
  material: '351:1'
  #Set if you wan't the item has enchant
  glow: true
  #Message displayed when you die with uses itemrescuer
  deathsmsg: '&9Remaining Deaths: &6{DEATHS}'
  #Uses for itemrescuer
  deaths: -1
  #Name of itemrescuer
  name: '&9ItemRescuer'
  #When not owner player try to pick up the item display the owner in hologram
  displayonitem: true
  crafting:
    denied:
    #Denied items to bound
    - 268-271
    - '290'
    allowed:
    #Allowed items to bound
    - 256-258
    - 267-279
    - 283-286
    - 290-294
    - 298-317
    - '346'
  header: '&4[&6Item&eRescurer&4]'
  lore:
  - '&e&oPlace this item in crafting bench'
  - '&e&oAnd then place one item to save it'
  - '&dOnly have 1 use!'
puppet:
  messages:
    died: '&aYou save your inventory but you lose 1 puppet, now you have {REMAINIG}
      puppets!'
    get: '&aYou get {AMOUNT} puppets'
  header: '&2[&4Puppet&2]'
  name: '&2Puppet'
  glow: true
  craft:
    enabled: false
    shape:
    - 42,341,42
    - 42,351:2,42
    - 42,416,42
  lore:
  - '&e&oUse this item for save inventory on dead'
  - '&dOnly have 1 use!'
  material: '351:2'
itemrestriction:
  candrop: false
  enabled: true
  canitemframe: false
  armorstand: false
  canpetspick: false
  canpick: false
  allowedinventories:
  - CRAFTING
  - CREATIVE
  - ENCHANTING
  - ENDER_CHEST
  - PLAYER
  - WORKBENCH
  - PLUGIN_VAULT
messages:
  get:
    stringfull: '&cYou have full inventory then some items has been dropped'
  permission: '&cYou don''t have permission to use this command'
updatechecker: true
metrics: true
