name: ItemRescuer
main: mx.com.rodel.InventoryRescuer
description: Link all you stuff and don't lose it!
version: 1.3.11

commands:
  itemrescurer:
    description: ItemRescuer base command
    aliases: [ir, itemrescuer]